name: learn-github-actions
on: [push]
env:
  env_1: hashito
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "ths is env=${{ env.env_1 }}"
          echo ${{ github.action }}
